### Create
POST http://localhost:3000/repo HTTP/1.1
content-type: application/json

{
    "url": "https://github.com/othneildrew/Best-README-Template"
}

### FindeAll

GET http://localhost:3000/repos HTTP/1.1

### FindeOne
GET http://localhost:3000/repo/de1dd3e4-d96f-42a0-af93-02f57cb8b6f1 HTTP/1.1

### Update
PUT http://localhost:3000/repo/7ab7e644-c3df-4e2f-b698-3778c6303756 HTTP/1.1
content-type: application/json

{
    "name": "repo-thaz"
}

### Delete
DELETE http://localhost:3000/repo/2 HTTP/1.1