# POST http://localhost:3000/repo HTTP/1.1
# content-type: application/json

# {
#     "name": "repo-thalinho",
#     "url": "http://www.git.repo-test",
#     "author": "thalinho",
#     "topics": ["http", "test"]
# }
# https://github.com/othneildrew/Best-README-Template

### Get repository
GET https://api.github.com/repos/othneildrew/Best-README-Template HTTP/1.1